### PR TITLE
Added support for the Russian language

### PR DESCRIPTION
**Pull request by Nosfer54**
Hello! I plan to add support for the Russian language both in the application itself (for as long as possible) and in the main templates.

Please accept MR :)

### CODE REVIEW

**Comment by CajunAvenger** [comment]
Looks good. It looks like is_tribal and is_spell weren't translated, and word_lists_ru is missing. Think I've got the dictionary files MSE needs for Russian spell checking so just waiting out those.

**Comment by Nosfer54** [comment]
This process is not fast, I will gradually translate all the blocks (to start the interface), then I plan to go to templates (at least the main ones MTG)

**Comment by CajunAvenger** [comment]
have updated with a Russian (and the missing French) dictionary and some infrastructure files for further support. also included the French and Spanish versions of the english_number() script in the languages file, those may be helpful templates to make a Russian version.

**Comment by Nosfer54** [comment]
Sumptuously! Thank you very much.

Even on version 2.1.2 (win10, x64) I observe an error that I cannot enter non-English characters from the keyboard (everything is perfectly inserted from the clipboard)
This error here? or a separate issue to another repository?

**Comment by CajunAvenger** [comment]
> This error here? or a separate issue to another repository?

My guesses would it'd be some font thing or something from the [MSE source code](https://github.com/twanvl/MagicSetEditor2). Are you able to type in the Card notes area?

**Comment by Nosfer54** [comment]
All text on the image (both on the card and in the "Card notes" field) was entered through copying from the clipboard. We used the template magic-m15-altered.mse-style with support for the Russian font "Cambria".
When typing from the keyboard with a layout that is not equal to "en", nothing happens :) On version 2.0.0, this problem was not observed :)

**Pull request merged**
