### PR TITLE
puma update

### PR DESCRIPTION
**Pull request by Cardists**
Updates the PUMA style to more closely represent the original style.

### CODE REVIEW

**Comment by CajunAvenger** [comment]
this is looking good. is there any difference between the puma/ and shifted/ images? if there's not, the shifted_prefix for it should just be the same folder instead of including dupes of all the files.

mechanically, i'm gonna move this to the `scrolls` field for a little optimization, and enable this on conspiracy and season now

**Comment by Cardists** [comment]
Yes, there's a difference. But I think the only difference is for the artifact card. Because the shifted artifact color is brown and not silver. If you know of a way to make the puma images work for shifted without making dupes for everything except for the artifact card, then go ahead. Because I don't. I've mentioned in the forums that the PUMA style is the old style for extended art. I will see if I can make an extra option to change the PUMA style to match the newer extended art style (there's a few subtle differences).

**Comment by Cardists** [comment]
On an unrelated note, I've sort of got ahead of myself and forgot to ask. Are you working on the M21 alternate-art borderless card style? Just asking, because I was working on it. [I've asked this in the MSE forums.](https://magicseteditor.boards.net/thread/77/cajun-style-templates-classes-showcases?page=35&scrollTo=36524)
[Example of the style](https://scryfall.com/search?order=set&q=set%3Am21+border%3Aborderless+-type%3Aplaneswalker&unique=prints)

**Comment by CajunAvenger** [comment]
i usually don't do promo frames that get used once and then dropped, but if someone blanks them i'll put them to templates

**Comment by RadSuit** [comment]
I was commenting on my alt account, this is my main. How come you don't comma separate all the objects in the prefix and suffix arrays? Also, did you ever figure out how to separate the planeshifted artifact card from the normal cards? Because, I struggled trying to get some code going that specifically targets generic colored artifact cards, to no avail. The closest I got was applying the planeshifted artifact puma image to planeshifted artifact cards. But it would be applied to WUBRG artifacts as well. I was going to update this by moving the assets to a subfolder in the puma folder, but that's up to you. Would you prefer the assets stay in the shifted folder or give them their own folder? Also, I'm still working on that extra option for puma. If this doesn't get merged before I'm done with it, I will update this pull request with that code. If this is merged before I'm done with it, I will make a new request with that code.

**Comment by Cardists** [comment]
This change removes two unnecessary files and adds an option to chose between m18 or m19+ styled extended art.

**Comment by Cardists** [comment]
How do I resolve this conflict while also adding the "not" operator for is_extended_art()? This conflict seems to be non-issue.

**Comment by CajunAvenger** [comment]
bleh managing pull requests with git is always pulling teeth
trying to figure out how to resolve and get this to master in the next few days

**Comment by CajunAvenger** [comment]
is_m21_full_art is not defined on the current style

**Comment by Cardists** [comment]
Sorry, that was a leftover from a copy and paste. I'll make sure there's no leftover edits next time, thank you for merging the pull.

**Review by Cardists — COMMENTED** [review]
I'm still somewhat a noob when it comes to C++ coding, so I noticed some unnecessary syntax in line 1564. The next time you update your style files please just remove the {""} surrounding the puma.png. It isn't necessary because it's just a string, not a statement.

**Pull request merged**
